Search.appendIndex(
    [
                {
            "fqsen": "\\Pedido",
            "name": "Pedido",
            "summary": "",
            "url": "classes/Pedido.html"
        },                {
            "fqsen": "\\Pedido\u003A\u003AsetIdPedido\u0028\u0029",
            "name": "setIdPedido",
            "summary": "",
            "url": "classes/Pedido.html#method_setIdPedido"
        },                {
            "fqsen": "\\Pedido\u003A\u003AsetIdProducto\u0028\u0029",
            "name": "setIdProducto",
            "summary": "",
            "url": "classes/Pedido.html#method_setIdProducto"
        },                {
            "fqsen": "\\Pedido\u003A\u003AsetNombreUsuario\u0028\u0029",
            "name": "setNombreUsuario",
            "summary": "",
            "url": "classes/Pedido.html#method_setNombreUsuario"
        },                {
            "fqsen": "\\Pedido\u003A\u003AcrearPedido\u0028\u0029",
            "name": "crearPedido",
            "summary": "",
            "url": "classes/Pedido.html#method_crearPedido"
        },                {
            "fqsen": "\\Pedido\u003A\u003A\u0024id_pedido",
            "name": "id_pedido",
            "summary": "",
            "url": "classes/Pedido.html#property_id_pedido"
        },                {
            "fqsen": "\\Pedido\u003A\u003A\u0024id_producto",
            "name": "id_producto",
            "summary": "",
            "url": "classes/Pedido.html#property_id_producto"
        },                {
            "fqsen": "\\Pedido\u003A\u003A\u0024nombre_usuario",
            "name": "nombre_usuario",
            "summary": "",
            "url": "classes/Pedido.html#property_nombre_usuario"
        },                {
            "fqsen": "\\Producto",
            "name": "Producto",
            "summary": "",
            "url": "classes/Producto.html"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetNombre\u0028\u0029",
            "name": "getNombre",
            "summary": "",
            "url": "classes/Producto.html#method_getNombre"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetPrecio\u0028\u0029",
            "name": "getPrecio",
            "summary": "",
            "url": "classes/Producto.html#method_getPrecio"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetIdProducto\u0028\u0029",
            "name": "getIdProducto",
            "summary": "",
            "url": "classes/Producto.html#method_getIdProducto"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetDescripcion\u0028\u0029",
            "name": "getDescripcion",
            "summary": "",
            "url": "classes/Producto.html#method_getDescripcion"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetLikes\u0028\u0029",
            "name": "getLikes",
            "summary": "",
            "url": "classes/Producto.html#method_getLikes"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetDeporte\u0028\u0029",
            "name": "getDeporte",
            "summary": "",
            "url": "classes/Producto.html#method_getDeporte"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetImagen\u0028\u0029",
            "name": "getImagen",
            "summary": "",
            "url": "classes/Producto.html#method_getImagen"
        },                {
            "fqsen": "\\Producto\u003A\u003AsetNombre\u0028\u0029",
            "name": "setNombre",
            "summary": "",
            "url": "classes/Producto.html#method_setNombre"
        },                {
            "fqsen": "\\Producto\u003A\u003AsetPrecio\u0028\u0029",
            "name": "setPrecio",
            "summary": "",
            "url": "classes/Producto.html#method_setPrecio"
        },                {
            "fqsen": "\\Producto\u003A\u003AsetIdProducto\u0028\u0029",
            "name": "setIdProducto",
            "summary": "",
            "url": "classes/Producto.html#method_setIdProducto"
        },                {
            "fqsen": "\\Producto\u003A\u003AsetDescripcion\u0028\u0029",
            "name": "setDescripcion",
            "summary": "",
            "url": "classes/Producto.html#method_setDescripcion"
        },                {
            "fqsen": "\\Producto\u003A\u003AsetLikes\u0028\u0029",
            "name": "setLikes",
            "summary": "",
            "url": "classes/Producto.html#method_setLikes"
        },                {
            "fqsen": "\\Producto\u003A\u003AsetDeporte\u0028\u0029",
            "name": "setDeporte",
            "summary": "",
            "url": "classes/Producto.html#method_setDeporte"
        },                {
            "fqsen": "\\Producto\u003A\u003AsetImagen\u0028\u0029",
            "name": "setImagen",
            "summary": "",
            "url": "classes/Producto.html#method_setImagen"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetAllProducts\u0028\u0029",
            "name": "getAllProducts",
            "summary": "",
            "url": "classes/Producto.html#method_getAllProducts"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetProductByName\u0028\u0029",
            "name": "getProductByName",
            "summary": "",
            "url": "classes/Producto.html#method_getProductByName"
        },                {
            "fqsen": "\\Producto\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Producto.html#method_create"
        },                {
            "fqsen": "\\Producto\u003A\u003AupdateProduct\u0028\u0029",
            "name": "updateProduct",
            "summary": "",
            "url": "classes/Producto.html#method_updateProduct"
        },                {
            "fqsen": "\\Producto\u003A\u003AdeleteProduct\u0028\u0029",
            "name": "deleteProduct",
            "summary": "",
            "url": "classes/Producto.html#method_deleteProduct"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetProductById\u0028\u0029",
            "name": "getProductById",
            "summary": "",
            "url": "classes/Producto.html#method_getProductById"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetTopLikedProducts\u0028\u0029",
            "name": "getTopLikedProducts",
            "summary": "",
            "url": "classes/Producto.html#method_getTopLikedProducts"
        },                {
            "fqsen": "\\Producto\u003A\u003AgetProductBySport\u0028\u0029",
            "name": "getProductBySport",
            "summary": "",
            "url": "classes/Producto.html#method_getProductBySport"
        },                {
            "fqsen": "\\Producto\u003A\u003AsearchProducts\u0028\u0029",
            "name": "searchProducts",
            "summary": "",
            "url": "classes/Producto.html#method_searchProducts"
        },                {
            "fqsen": "\\Producto\u003A\u003A\u0024nombre_producto",
            "name": "nombre_producto",
            "summary": "",
            "url": "classes/Producto.html#property_nombre_producto"
        },                {
            "fqsen": "\\Producto\u003A\u003A\u0024precio",
            "name": "precio",
            "summary": "",
            "url": "classes/Producto.html#property_precio"
        },                {
            "fqsen": "\\Producto\u003A\u003A\u0024id_producto",
            "name": "id_producto",
            "summary": "",
            "url": "classes/Producto.html#property_id_producto"
        },                {
            "fqsen": "\\Producto\u003A\u003A\u0024likes",
            "name": "likes",
            "summary": "",
            "url": "classes/Producto.html#property_likes"
        },                {
            "fqsen": "\\Producto\u003A\u003A\u0024deporte",
            "name": "deporte",
            "summary": "",
            "url": "classes/Producto.html#property_deporte"
        },                {
            "fqsen": "\\Producto\u003A\u003A\u0024descripcion",
            "name": "descripcion",
            "summary": "",
            "url": "classes/Producto.html#property_descripcion"
        },                {
            "fqsen": "\\Producto\u003A\u003A\u0024imagen",
            "name": "imagen",
            "summary": "",
            "url": "classes/Producto.html#property_imagen"
        },                {
            "fqsen": "\\Rese\u00F1a",
            "name": "Rese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AgetIdrese\u00F1a\u0028\u0029",
            "name": "getIdrese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html#method_getIdrese%C3%B1a"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AgetTexto\u0028\u0029",
            "name": "getTexto",
            "summary": "",
            "url": "classes/Resena.html#method_getTexto"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AgetPuntuacion\u0028\u0029",
            "name": "getPuntuacion",
            "summary": "",
            "url": "classes/Resena.html#method_getPuntuacion"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AgetNombreUsuariorese\u00F1a\u0028\u0029",
            "name": "getNombreUsuariorese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html#method_getNombreUsuariorese%C3%B1a"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AgetIdProductorese\u00F1a\u0028\u0029",
            "name": "getIdProductorese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html#method_getIdProductorese%C3%B1a"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AsetTexto\u0028\u0029",
            "name": "setTexto",
            "summary": "",
            "url": "classes/Resena.html#method_setTexto"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AsetPuntuacion\u0028\u0029",
            "name": "setPuntuacion",
            "summary": "",
            "url": "classes/Resena.html#method_setPuntuacion"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AsetNombreUsuarioRese\u00F1a\u0028\u0029",
            "name": "setNombreUsuarioRese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html#method_setNombreUsuarioRese%C3%B1a"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AsetIdProductoRese\u00F1a\u0028\u0029",
            "name": "setIdProductoRese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html#method_setIdProductoRese%C3%B1a"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AgetAllRese\u00F1as\u0028\u0029",
            "name": "getAllRese\u00F1as",
            "summary": "",
            "url": "classes/Resena.html#method_getAllRese%C3%B1as"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AgetRese\u00F1asByProduct\u0028\u0029",
            "name": "getRese\u00F1asByProduct",
            "summary": "",
            "url": "classes/Resena.html#method_getRese%C3%B1asByProduct"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Resena.html#method_create"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003AdeleteRese\u00F1a\u0028\u0029",
            "name": "deleteRese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html#method_deleteRese%C3%B1a"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003A\u0024id_rese\u00F1a",
            "name": "id_rese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html#property_id_rese%C3%B1a"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003A\u0024texto",
            "name": "texto",
            "summary": "",
            "url": "classes/Resena.html#property_texto"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003A\u0024puntuacion",
            "name": "puntuacion",
            "summary": "",
            "url": "classes/Resena.html#property_puntuacion"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003A\u0024nombre_usuario_rese\u00F1a",
            "name": "nombre_usuario_rese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html#property_nombre_usuario_rese%C3%B1a"
        },                {
            "fqsen": "\\Rese\u00F1a\u003A\u003A\u0024id_producto_rese\u00F1a",
            "name": "id_producto_rese\u00F1a",
            "summary": "",
            "url": "classes/Resena.html#property_id_producto_rese%C3%B1a"
        },                {
            "fqsen": "\\Usuario",
            "name": "Usuario",
            "summary": "Clase\u0020que\u0020representa\u0020a\u0020un\u0020usuario\u0020en\u0020el\u0020sistema",
            "url": "classes/Usuario.html"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetNombreUsuario\u0028\u0029",
            "name": "getNombreUsuario",
            "summary": "Obtiene\u0020el\u0020nombre\u0020de\u0020usuario",
            "url": "classes/Usuario.html#method_getNombreUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetCorreo\u0028\u0029",
            "name": "getCorreo",
            "summary": "Obtiene\u0020el\u0020correo\u0020electr\u00F3nico\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getCorreo"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetNombreApellidos\u0028\u0029",
            "name": "getNombreApellidos",
            "summary": "Obtiene\u0020el\u0020nombre\u0020y\u0020apellidos\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getNombreApellidos"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetContrase\u00F1a\u0028\u0029",
            "name": "getContrase\u00F1a",
            "summary": "Obtiene\u0020la\u0020contrase\u00F1a\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getContrase%C3%B1a"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetDireccion\u0028\u0029",
            "name": "getDireccion",
            "summary": "Obtiene\u0020la\u0020direcci\u00F3n\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getDireccion"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetNombreUsuario\u0028\u0029",
            "name": "setNombreUsuario",
            "summary": "Establece\u0020el\u0020nombre\u0020de\u0020usuario",
            "url": "classes/Usuario.html#method_setNombreUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetCorreo\u0028\u0029",
            "name": "setCorreo",
            "summary": "Establece\u0020el\u0020correo\u0020electr\u00F3nico\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setCorreo"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetNombreApellidos\u0028\u0029",
            "name": "setNombreApellidos",
            "summary": "Establece\u0020el\u0020nombre\u0020y\u0020apellidos\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setNombreApellidos"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetDireccion\u0028\u0029",
            "name": "setDireccion",
            "summary": "Establece\u0020la\u0020direcci\u00F3n\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setDireccion"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetContrase\u00F1a\u0028\u0029",
            "name": "setContrase\u00F1a",
            "summary": "Establece\u0020la\u0020contrase\u00F1a\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setContrase%C3%B1a"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetAllUsers\u0028\u0029",
            "name": "getAllUsers",
            "summary": "Obtiene\u0020todos\u0020los\u0020usuarios\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_getAllUsers"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetUserByName\u0028\u0029",
            "name": "getUserByName",
            "summary": "Obtiene\u0020un\u0020usuario\u0020por\u0020su\u0020nombre\u0020de\u0020usuario",
            "url": "classes/Usuario.html#method_getUserByName"
        },                {
            "fqsen": "\\Usuario\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Crea\u0020un\u0020nuevo\u0020usuario",
            "url": "classes/Usuario.html#method_create"
        },                {
            "fqsen": "\\Usuario\u003A\u003AupdateUser\u0028\u0029",
            "name": "updateUser",
            "summary": "Actualiza\u0020los\u0020datos\u0020del\u0020usuario\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_updateUser"
        },                {
            "fqsen": "\\Usuario\u003A\u003AdeleteUser\u0028\u0029",
            "name": "deleteUser",
            "summary": "Elimina\u0020un\u0020usuario\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_deleteUser"
        },                {
            "fqsen": "\\Usuario\u003A\u003AupdateNombreUsuario\u0028\u0029",
            "name": "updateNombreUsuario",
            "summary": "Actualiza\u0020el\u0020nombre\u0020de\u0020usuario\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_updateNombreUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AupdateContrase\u00F1a\u0028\u0029",
            "name": "updateContrase\u00F1a",
            "summary": "Actualiza\u0020la\u0020contrase\u00F1a\u0020del\u0020usuario\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_updateContrase%C3%B1a"
        },                {
            "fqsen": "\\Usuario\u003A\u003AupdateNombreApellidos\u0028\u0029",
            "name": "updateNombreApellidos",
            "summary": "Actualiza\u0020el\u0020nombre\u0020y\u0020apellidos\u0020del\u0020usuario\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_updateNombreApellidos"
        },                {
            "fqsen": "\\Usuario\u003A\u003AupdateDireccion\u0028\u0029",
            "name": "updateDireccion",
            "summary": "Actualiza\u0020la\u0020direcci\u00F3n\u0020del\u0020usuario\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_updateDireccion"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024nombre_usuario",
            "name": "nombre_usuario",
            "summary": "",
            "url": "classes/Usuario.html#property_nombre_usuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024correo",
            "name": "correo",
            "summary": "",
            "url": "classes/Usuario.html#property_correo"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024nombreapellidos",
            "name": "nombreapellidos",
            "summary": "",
            "url": "classes/Usuario.html#property_nombreapellidos"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024direccion",
            "name": "direccion",
            "summary": "",
            "url": "classes/Usuario.html#property_direccion"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024contrase\u00F1a",
            "name": "contrase\u00F1a",
            "summary": "",
            "url": "classes/Usuario.html#property_contrase%C3%B1a"
        },                {
            "fqsen": "\\Wishlist",
            "name": "Wishlist",
            "summary": "",
            "url": "classes/Wishlist.html"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AgetIdWishlist\u0028\u0029",
            "name": "getIdWishlist",
            "summary": "",
            "url": "classes/Wishlist.html#method_getIdWishlist"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AgetNombreUsuario\u0028\u0029",
            "name": "getNombreUsuario",
            "summary": "",
            "url": "classes/Wishlist.html#method_getNombreUsuario"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AgetIdProducto\u0028\u0029",
            "name": "getIdProducto",
            "summary": "",
            "url": "classes/Wishlist.html#method_getIdProducto"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AsetIdWishlist\u0028\u0029",
            "name": "setIdWishlist",
            "summary": "",
            "url": "classes/Wishlist.html#method_setIdWishlist"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AsetNombreUsuario\u0028\u0029",
            "name": "setNombreUsuario",
            "summary": "",
            "url": "classes/Wishlist.html#method_setNombreUsuario"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AsetIdProducto\u0028\u0029",
            "name": "setIdProducto",
            "summary": "",
            "url": "classes/Wishlist.html#method_setIdProducto"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AgetAllWishlists\u0028\u0029",
            "name": "getAllWishlists",
            "summary": "",
            "url": "classes/Wishlist.html#method_getAllWishlists"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AgetWishlistByUser\u0028\u0029",
            "name": "getWishlistByUser",
            "summary": "",
            "url": "classes/Wishlist.html#method_getWishlistByUser"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AgetWishlistById\u0028\u0029",
            "name": "getWishlistById",
            "summary": "",
            "url": "classes/Wishlist.html#method_getWishlistById"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AaddProductToWishlist\u0028\u0029",
            "name": "addProductToWishlist",
            "summary": "",
            "url": "classes/Wishlist.html#method_addProductToWishlist"
        },                {
            "fqsen": "\\Wishlist\u003A\u003AremoveProductFromWishlist\u0028\u0029",
            "name": "removeProductFromWishlist",
            "summary": "",
            "url": "classes/Wishlist.html#method_removeProductFromWishlist"
        },                {
            "fqsen": "\\Wishlist\u003A\u003A\u0024id_wishlist",
            "name": "id_wishlist",
            "summary": "",
            "url": "classes/Wishlist.html#property_id_wishlist"
        },                {
            "fqsen": "\\Wishlist\u003A\u003A\u0024nombre_usuario",
            "name": "nombre_usuario",
            "summary": "",
            "url": "classes/Wishlist.html#property_nombre_usuario"
        },                {
            "fqsen": "\\Wishlist\u003A\u003A\u0024id_producto",
            "name": "id_producto",
            "summary": "",
            "url": "classes/Wishlist.html#property_id_producto"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
